<div id="block-sample-grid" data-bind="scope:'sample-grid'" class="block">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "#block-sample-grid": {
            "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
        }
    }
</script>
<script>
    window.grid_data = <?= $block->getValues();?>
</script>