<div id="custom-component" data-bind="scope:'customcomponent'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
    <script type="text/x-magento-init">
    {
        "#custom-component": {
            "Magento_Ui/js/core/app": {
               "components": {
                    "customcomponent": {
                        "component": "Kitchen_KnockoutTask/js/custom-component"
                    }
                }
            }
        }
    }
    </script>
    
    <script>
        window.grid_data = '1';
    </script>